export const CustomImages = {
  secureEye: require("./Images/closeEyeIcon.png"),
  unSecureEye: require("./Images/openEye.png"),
  mailIcon: require("./Images/mailIcon.png"),
  logo: require("./Images/logo.png"),
  logoBackground:require("./Images/logoBackground.png"),
  dropDownIcon:require("./Images/dropDownIcon.png"),
  blackDropDownIcon:require("./Images/blackDropDownIcon.png"),
  arrowIcon:require("./Images/Arrow.png"),
  whiteDot:require("./Images/circledot.png"),
  profilePic:require("./Images/profilePic.png"),
  closeIcon:require("./Images/closeIcon.png"),
  photoGallery:require("./Images/album.png"),
  cameraIcon:require("./Images/camera.png"),
  refreshIcon:require("./Images/Icon-Refresh.png"),
  maleBody:require("./Images/maleBody.png"),
  femaleBody:require("./Images/femaleBody.png"),
  multiSelect:require("./Images/multiSelect.png"),
};
